sudo: required
services:
  - docker

before_install:
  - docker build -t xantko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xantko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "elastic-beanstalk"
  env: "Elastic-beanstalk-env"
  bucket_name: "elasticbeanstalk-eu-north-1-642502856457"
  bucket_path: "elastic-beanstalk"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"